version: '3.9'

services:
  backend:
    build: ./backend-springboot
    container_name: scifilearn-backend
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - mistral
      - ollama

  frontend:
    build: ./frontend
    container_name: scifilearn-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mistral:
    image: ghcr.io/mistralai/mistral:latest
    container_name: mistral
    ports:
      - "5005:5005"

  ollama:
    image: ghcr.io/ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
